# Generated by Django 5.0.2 on 2024-03-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Age', models.IntegerField(blank=True, null=True)),
                ('user_Height', models.FloatField(blank=True, null=True)),
                ('user_Weight', models.FloatField(blank=True, null=True)),
                ('family_history_with_overweight', models.BooleanField(default=False)),
                ('FAVC', models.BooleanField(default=False)),
                ('FCVC', models.FloatField(blank=True, null=True)),
                ('SCC', models.BooleanField(default=False)),
                ('FAF', models.FloatField(blank=True, null=True)),
                ('TUE', models.FloatField(blank=True, null=True)),
                ('NCP', models.IntegerField(blank=True, null=True)),
                ('CAEC', models.CharField(blank=True, max_length=10, null=True)),
                ('Smoke', models.BooleanField(default=False)),
                ('CH2O', models.FloatField(blank=True, null=True)),
                ('CALC', models.CharField(blank=True, max_length=10, null=True)),
                ('Transportation', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
