# Generated by Django 5.0.2 on 2024-03-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_alter_health_caec_alter_health_calc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
